// Generated by Haxe 4.3.6
(function ($global) { "use strict";
var Main = function() {
	this.canvas = window.document.createElement("canvas");
	this.canvas.width = window.innerWidth;
	this.canvas.height = window.innerHeight;
	window.document.body.appendChild(this.canvas);
	this.ctx = this.canvas.getContext("2d",null);
	window.requestAnimationFrame($bind(this,this.update));
};
Main.main = function() {
	new Main();
};
Main.prototype = {
	update: function(time_ms) {
		this.ctx.clearRect(0,0,this.canvas.width,this.canvas.height);
		this.ctx.fillStyle = "rgb(200 0 0)";
		this.ctx.fillRect(100 + Math.sin(time_ms * .01) * 100,10,50,50);
		window.requestAnimationFrame($bind(this,this.update));
	}
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
var $_;
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $global.$haxeUID++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = m.bind(o); o.hx__closures__[m.__id__] = f; } return f; }
$global.$haxeUID |= 0;
Main.main();
})(typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);
